{
 "title": "ML Detection Results",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Coordinate Pattern (Anomaly Detection)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT MOVING_AVERAGE(last(\"coord\"), 5) FROM \"joints\" WHERE $timeFilter GROUP BY time(3s) fill(linear)",
     "select": [
      [
       { "params": [ "servo_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT coord FROM \"detection\" WHERE $timeFilter AND is_anomalous ='True'"
    }
   ]
  },
  {
   "title": "Anomaly Count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(coord) FROM \"detection\" WHERE $timeFilter AND is_anomalous ='True'"
    }
   ]
  },
  {
   "title": "MSE Percentage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT mse_percentage FROM \"detection\" WHERE $timeFilter"
    }
   ]
  }
 ]
}