{
 "title": "Robot Monitoring",
 "time": { "from": "2023-10-11T14:05:17.189Z", "to": "2023-10-11T14:08:34.317Z" },
 "panels": [
  { "title": "Robot Primary Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Moving",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "status",
     "query": "SELECT last(\"moving\") FROM \"status\" WHERE $timeFilter GROUP BY time(2s) fill(previous)",
     "select": [
      [
       { "params": [ "moving" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Robot Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status",
     "query": "SELECT last(\"speed\") FROM \"status\" WHERE $timeFilter GROUP BY time(5s) fill(linear)",
     "select": [
      [
       { "params": [ "moving" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Joint Speed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT last(\"servo_speed\") FROM \"robot\".\"joints\" WHERE $timeFilter GROUP BY joint",
     "select": [
      [
       { "params": [ "servo_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Joint Monitoring ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Servo Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT mean(\"servo_temp\") FROM \"joints\" WHERE $timeFilter GROUP BY time($__interval), \"joint\"::tag fill(previous)",
     "select": [
      [
       { "params": [ "servo_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Servo Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT mean(\"servo_speed\") FROM \"joints\" WHERE $timeFilter GROUP BY time($__interval), \"joint\"::tag fill(previous)",
     "select": [
      [
       { "params": [ "servo_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Servo Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT mean(\"servo_voltage\") FROM \"joints\" WHERE  $timeFilter GROUP BY time($__interval), \"joint\"::tag fill(previous)",
     "select": [
      [
       { "params": [ "servo_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coordinate Pattern (LAST)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT last(\"coord\") FROM \"joints\" WHERE  $timeFilter  GROUP BY time(2s) fill(linear)",
     "select": [
      [
       { "params": [ "servo_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coordinate Pattern (DERIVATIVE)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT DERIVATIVE(last(\"coord\"), 1s) FROM \"joints\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "servo_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coordinate Pattern (MOVING_AVERAGE)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT MOVING_AVERAGE(last(\"coord\"), 5) FROM \"joints\" WHERE $timeFilter GROUP BY time(3s) fill(linear)",
     "select": [
      [
       { "params": [ "servo_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coordinate Pattern (MOVING_AVERAGE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "joint::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "joints",
     "query": "SELECT MOVING_AVERAGE(last(\"coord\"), 5) FROM \"joints\" WHERE $timeFilter GROUP BY time(3s) fill(linear)",
     "select": [
      [
       { "params": [ "servo_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT coord FROM \"detection\" WHERE $timeFilter AND is_anomalous ='True'"
    }
   ]
  }
 ]
}